---
title: "Curriculum Vitae"
description: |
  Professional information about Karina
---

```{r setup, include = FALSE, warnings = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

<a href = “K.Johnston_CV_Jan2022.pdf” target = “_blank” > Click here for a full CV (pdf)</a>


## Interests and Experience

Karina Johnston has been a passionate scientific and community leader in the southern California region for more than 14 years, with an increasing level of responsibility culminating in her current position with The Bay Foundation as Science Director and her current position with Loyola Marymount University as Director of Programs for LMU’s Coastal Research Institute. Karina leads her department at TBF by developing, managing, and implementing federal, state, and non-profit grants to help execute the strategic plan for the Santa Monica Bay National Estuary Program, which strives to clean up waterways and create healthy habitats in the Los Angeles region. She is currently directing multiple projects to research and restore coastal habitats, including beaches, dunes, and wetlands. Career ecological restoration highlights include project implementation and leading the scientific monitoring programs for the Malibu Lagoon Restoration and Enhancement Project, the Santa Monica Beach Restoration Pilot Project, several other Living Shoreline Projects, and contributing significantly to environmental planning (CEQA/NEPA) for the Ballona Wetlands Restoration Project (577 acres).

As CRI’s Director of Programs, she developed and oversees the internship and faculty fellowship programs, conducts research, and teaches in Environmental Science. Current research fields include coastal ecology, coastal resiliency, restoration ecology, and water quality. In 2021, Karina won the Part Time Faculty Distinguished Teaching Award from LMU for her teaching and research service.

Karina is recently finished leading the multi-year public process to perform major revisions to regional strategic plans, including a revised Comprehensive Monitoring Program and Climate Action Plan for the region. Karina is also a Board Certified Environmental Scientist, with a Biology specialty and is a Certified Ecological Restoration Practitioner (Society for Ecological Restoration). In 2021, Karina began a PhD program at UCSB in Environmental Science and aims to conduct research relating to ecological and physical trajectories of beach restoration projects in southern California in partnership with her academic and community mentors.

## Publications and Peer Reviewed Technical Documents (selected)

Burkhard, J, K Johnston, J Saez, and J Dorsey.  Water Quality and Hydrological Benefits of a Natural Treatment System Installed in an Urban Watershed in Southern California. (submitted) Environmental Monitoring and Assessment.

Rosenau, N, H Galavotti, et al., including K Johnston (2021). Integrating High-Resolution Coastal Acidification Monitoring Data Across Seven U.S. Estuaries. Frontiers in Marine Science, Vol. 8: 679913. DOI: 10.3389/fmars.2021.679913

Johnston, K., C. Enyart, M. Jenkins, D. Lazarus, and S. Cuadra (2021). Santa Monica Beach Restoration Pilot Project: Year 5 Annual Report. Report prepared by The Bay Foundation for City of Santa Monica, California Coastal Commission, US Environmental Protection Agency, and California Department of Parks and Recreation. 118 pages.

Johnston, K, C Enyart, M Jenkins, S Cuadra, and D Lazarus (2021). Los Angeles Living Shoreline Project Restoration and Monitoring Plan. Prepared by The Bay Foundation for the California Coastal Commission, Los Angeles County Department of Beaches and Harbors, City of Los Angeles, and State Coastal Conservancy. 72 pages.

Grifman, P, M Grubbs, and K Johnston (2020).  From Science to Adaptation: A Case Study in Nature-Based Adaptation to Improve Coastal Resiliency in Santa Monica Bay. Shore and Beach, Vol. 88 (3), pp. 39-52. DOI: 10.34237/1008834 

Harvey, M, SN Giddings, ED Stein, J Crooks, C Whitcraft, T Gallien, L Tiefenthaler, H Meltzer, G Pawlak, K Thorne, K Johnston, R Ambrose, S Schroeter, HM Page, and H Elwany (2020).  Effects of Elevated Sea Levels and Waves on Southern California Estuaries during the 2015–2016 El Niño. Estuaries and Coasts, Vol 43, pp. 256–271. DOI: 10.1007/s12237-019-00676-1 

Johnston, K, C. Enyart, K Alvarez, and H Weyland (2020). Santa Monica Beach Restoration Pilot Project Year 4 Annual Report.  Report prepared by The Bay Foundation for the City of Santa Monica, California Coastal Commission, US Environmental Protection Agency, and California Department of Parks and Recreation. 100 pp.

Ryan, TP, DS Cooper, S Vigallon, C Dellith, KK Johnston, and L Nguyen (2019).  Return of Beach Nesting Snowy Plovers to Los Angeles County Following a 68-Year Absence.  Western Birds 50: 16-25 DOI: 10.21199/WB50.1.2

Johnston, KK, M Grubbs, C Enyart, R Dagit, and D Cooper (2019). Malibu Lagoon Restoration and Enhancement Project Final Comprehensive Monitoring Report (Year 6). Report Prepared by The Bay Foundation for the State of California, Department of Parks and Recreation. 261 pp.

Johnston, K, M Grubbs, and R Abbott (2018). Santa Monica Beach Restoration Pilot Project Year 2 Annual Report.  Report prepared by The Bay Foundation for the City of Santa Monica, California Coastal Commission, Metabolic Studio, US Environmental Protection Agency, and California Department of Parks and Recreation. 67 pp.

Abramson, M, K Johnston, M Grubbs, R Abbott, R Dagit, and D Cooper (2018). Malibu Lagoon Restoration and Enhancement Project Comprehensive Monitoring Report (Year 5). Report Prepared for the State of California, Department of Parks and Recreation. 170 pp.

Abbott, R, M, Grubbs, and K Johnston (2018). Los Angeles International Airport Coastal Dunes Improvement Project Ecological Monitoring Report. Report Prepared for Los Angeles World Airports, City of LA and CA Coastal Commission. 60 pp.

Johnston, K, M Grubbs, and R Abbott (2017). Santa Monica Beach Restoration Pilot Project Year 1 Annual Report.  Report prepared by The Bay Foundation for the City of Santa Monica, California Coastal Commission, Metabolic Studio, US Environmental Protection Agency, and California Department of Parks and Recreation. 68 pp.

Abramson, M, K Johnston, R Abbott, M Grubbs, R Dagit, and D Cooper (2017). Malibu Lagoon Restoration and Enhancement Project Comprehensive Monitoring Report (Year 4). Report Prepared for the State of California, Department of Parks and Recreation. 175 pp.

Barton, ML, ID Medel, KK Johnston, and CR Whitcraft (2016). Seed Collection and Germination Strategies for Common Wetland and Coastal Sage Scrub Species in Southern California.  Bulletin of the Southern California Academy of Sciences, Vol 115(1).

Grubbs, M, K Johnston, G Wang, and T Ford (2016).  Climate Change Vulnerability Assessment of the Santa Monica Bay National Estuary Program’s Bay Restoration Plan.  Final Report prepared by the Santa Monica Bay National Estuary Program for the United States Environmental Protection Agency. 30 September 2016. 184 pp.

Abramson, M, K Johnston, R Abbott, M Grubbs, R Dagit, and D Cooper (2016). Malibu Lagoon Restoration and Enhancement Project Comprehensive Monitoring Report (Year 3). Report Prepared for the State of California, Department of Parks and Recreation. 148 pp.

Johnston, KK, J Dorsey, and J Saez (2015). Fecal Indicator Bacteria (FIB) Stratification and Loading in a Tidally Muted Urban Salt Marsh.  Environmental Monitoring and Assessment: DOI: 10.1007/s10661-015-4314-z

Ambrose, RF, JH Dorsey, KK Johnston, and ED Stein (2015). State of the Bay Report. “Habitat Conditions: Coastal Wetlands.” Urban Coast 5(1): 59-68.

Foreman, K, D Hubbard, KK Johnston, and K Martin (2015). State of the Bay Report. “Habitat Conditions: Sandy Shores.” Urban Coast 5(1): 69-84.

Johnston, KK, ID Medel, S Anderson, E Stein, C Whitcraft, and J Crooks (2015). California Estuarine Wetland Monitoring Manual (Level 3). Prepared by The Bay Foundation for the United States Environmental Protection Agency. 297 pages.

Johnston, KK, ID Medel, S Anderson, R Abbott, and E Stein (2015). Regional Monitoring Report for Southern California Coastal Wetlands: Application of the USEPA Three-Tiered Monitoring Strategy. Prepared by The Bay Foundation for the United States Environmental Protection Agency. 100 pages. 

Johnston, KK, ID Medel, and C Solek (2015). Condition Assessment of the Wetland Habitats in the Ballona Wetlands Ecological Reserve, Los Angeles, CA. Technical Memorandum prepared for the California State Coastal Conservancy and the California Department of Fish and Wildlife, 11 pp.

Abramson, M, K Johnston, I Medel, R Dagit, D Cooper, and R Abbott (2015). Malibu Lagoon Restoration and Enhancement Project Comprehensive Monitoring Report (Year 2). Report Prepared for the State of California, Department of Parks and Recreation. 135 pp.

Johnston, KK, I Medel, A McCarthy, and T Harris (2014).  Salt Pan Assessment to Inform Restoration Target Acreages at the Ballona Wetlands Ecological Reserve.  Technical Memorandum prepared for the California State Coastal Conservancy and the California Department of Fish and Wildlife, 16 pp.

Johnston, KK (2014). Socio-Economic Analyses of Coastal Ecosystem Resilience: Symposium Proceedings Document.  Hosted by the Santa Monica Bay Restoration Commission and the Center for Urban Resilience, March 2014; 23 pp.

Medel, ID, K Johnston, and A McCarthy (2014). Ballona Wetlands Ecological Reserve Vegetation Alliance and Habitat Crosswalk.  Technical Memorandum prepared for the California State Coastal Conservancy and the California Department of Fish and Wildlife, 22 pp.

McLaughlin, K, M Sutula, L Busse, S Anderson, J Crooks, R Dagit, D Gibson, K Johnston, and L Stratton (2013). A Regional Survey of Extent and Magnitude of Eutrophication in Southern California Estuaries.  Estuaries and Coasts: DOI: 10.1007/s12237-013-9670-8

Abramson, MA, R Dagit, DS Cooper, J King, KK Johnston, I Medel, and C Piechowski (2013). Malibu Lagoon Restoration and Enhancement Project Comprehensive Monitoring Report. Report prepared for the State of California Department of Parks and Recreation.

Johnston, KK (2013). Climate Change in Urban Estuaries: Symposium Proceedings Document.  Hosted by the Santa Monica Bay Restoration Commission and the Center for Urban Resilience, March 2013; 25 pp.

McLaughlin, K, M Sutula, L Busse, S Anderson, J Crooks, R Dagit, D Gibson, K Johnston, N Nezlin, and L Stratton. 2012. Southern California Bight 2008 Regional Monitoring Program: VIII. Estuarine Eutrophication. Southern California Coastal Water Research Project.  Costa Mesa, CA

Johnston, KK (2012).  Wetland Health and Assessment: An Information Inundation at the Ballona Wetlands Ecological Reserve.  Urban Coast (3)1: 61-70.

Johnston, KK, E Del Giudice-Tuttle, ID Medel, C Piechowski, D Cooper, J Dorsey, and S Anderson (2012). The Ballona Wetlands Ecological Reserve Baseline Assessment Program: 2010-2011 Report.  Santa Monica Bay Restoration Commission.  Report Prepared for the California State Coastal Conservancy, Los Angeles, California.  215 pp.

Johnston, KK, E Del Giudice-Tuttle, ID Medel, J Dorsey, D Cooper, and SP Bergquist (2011).  The Ballona Wetlands Ecological Reserve Baseline Assessment Program: 2009-2010.  Report prepared for the California State Coastal Conservancy and California Department of Fish and Game. 446 pp.

Del Giudice-Tuttle, E, KK Johnston, and ID Medel (2011). Evaluating Distribution and Prevalence of Non-native Vegetation in a Southern California Wetland and its Application to Inform Habitat Restoration and Non-native Vegetation Control.  Proceedings of the California Invasive Plant Council Symposium (15): 35-38.

Johnston, KK (2008).  Habitat Associations and Growth Patterns in Butterflyfish of Orpheus Island, Australia.  Submitted Master of Applied Science Thesis to James Cook University, Townsville, Australia, 77 pp.


