---
title: "Mono Lake Levels - Data Visualization"
author: "Karina Johnston"
output: 
  html_document: 
    theme: cerulean
    code_folding: hide
---

```{r setup, include = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Attach packages
library(tidyverse)
library(here)
library(janitor)
library(scales)
library(ggalt)

```


```{r}
# Read in the data

mono_lake <- read_csv(here("data", "mono_lake_annual_levels.csv"), 
                      skip = 5) %>% # skips the first five lines
  clean_names() # changes column headers to lower snake case

```


```{r}
mono_subset <- mono_lake %>% # creates a new subset dataframe
  select(c(year, lake_level_feet_above_sea_level)) %>% # selects only the needed columns
  rename(
    lake_level = lake_level_feet_above_sea_level # more manageable column header name
  )

```

<br>

```{r, fig.cap = "**Figure 1.** Mono Lake water levels in feet above sea level from 1850-2017 (Data: LADWP). Water levels include key environmental and political water limits and notations for major events. In 1941, LA Department of Water and Power began diversions; in 1994, the State Waterboard set a minimum required lake water level."}

# create a plot visualizing lake levels over time

ggplot(data = mono_subset, aes(x = year, 
                               y = lake_level)) +
  geom_line(color = "blue", size = 1.2) + # change aesthetics for line

# update limits and scales for the axes
  scale_y_continuous(limits = c(6355, 6430), 
                     breaks = seq(6360, 6470, 10),
                     label = comma) +
  scale_x_continuous(breaks = seq(1850, 2015, 20)) +

# add horizontal lines across the graph; lty is the style of line
  geom_hline(aes(yintercept = 6377), 
             color = "darkgreen", 
             lty = 4) +
  geom_hline(aes(yintercept = 6360), 
             color = "darkgreen", 
             lty = 4) +
  geom_hline(aes(yintercept = 6392), 
             color = "darkgreen", 
             lty = 4) +
  geom_xspline() + # smooths line

# add annotation labels on the graph for horizontal and vertical lines
  annotate("text", x = 1930, 
           y = 6380, 
           label = "Land Bridge Forms", 
           size = 4, 
           color = "black") +
  annotate("text", x = 1930, 
           y = 6363, 
           label = "Critical Food Availability", 
           size = 4, 
           color = "black") +
  annotate("text", x = 1930, 
           y = 6395, 
           label = "Minimum Lake Level", 
           size = 4, 
           color = "black") +
  annotate("text", x = 1966, 
           y = 6430, 
           label = "Water Diversion Begins", 
           size = 4, 
           color = "black") +
  annotate("text", x = 1994, 
           y = 6397, 
           label = "Lake Level Protected", 
           size = 4, 
           color = "black") +

# add vertical line segments with arrow to delineate major events
  geom_segment(aes(x = 1994, xend = 1994, 
                   y = 6394, yend = 6378),
               arrow = arrow(length = unit(0.3, "cm"))) +
  geom_segment(aes(x = 1941, xend = 1941, 
                   y = 6430, yend = 6418),
               arrow = arrow(length = unit(0.3, "cm"))) +
  
# update theme elements and labels
  theme_bw() + # cleaner graph output
  theme(plot.title = element_text(hjust = 0.5), # centers title
        panel.grid.minor = element_blank()) + # removes minor gridlines
  labs(x = "Year", # updates labels
       y = "Lake Level (ft above sea level)",
       title = "Mono Lake Water Levels (ft) from 1850-2017 (Johnston)") 

```


